### ISSUE TITLE
Image doesn't show

### ISSUE THREAD

**Issue by Kenny95** [paulbunyannet/image.php#3]
Hello,

image.php does work on localhost (xampp) but it doesn't work on my ftp server (online)

<img src="image.php/photo1.jpg?width=550&cropratio=1:1&image=/ds-deco/images/photos/photo1.jpg" alt="">

**Comment by natenolting** [comment]
@Kenny95 how are you calling image.php? What's the path you are using?

**Comment by Kenny95** [comment]
image.php/photo1.jpg?width=550&cropratio=1:1&image=/ds-deco/images/photos/photo1.jpg

**Comment by Kenny95** [comment]
I found what the issue was, 

thanks anyway :)
